export const USER_ACTION_TYPE ={
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CURRENT_TRANSFER: 'SET_CURRENT_TRANSFER',
    SET_CURRENT_LOAN:'SET_CURRENT_LOAN',
    // SORT_MOVEMENTS:'SORT_MOVEMENTS'
}